language: node_js

node_js:
  - 0.10
  - 0.12

script:
  - npm test

matrix:
  allow_failures:
    - node_js: 0.12
  fast_finish: true

before_install: npm install -g grunt-cli
install: npm install

after_script: NODE_ENV=test ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls && rm -rf ./coverage
